// Generated by CoffeeScript 1.4.0
(function() {
  var RR_AppendText, RR_BindEventListener, RR_LoadJQuerry, RR_Main, RR_RunEvent, RR_SetupInteractionZone, RR_StdinEvent, RR_StopEvent, prefix, socket;

  socket = void 0;

  prefix = '.present ';

  RR_Main = function() {
    socket = io.connect('http://localhost:8080');
    RR_SetupInteractionZone();
    return RR_BindEventListener();
  };

  RR_SetupInteractionZone = function() {
    var interactionZone;
    interactionZone = '<div class="RR_InteractionZone">\
			<button class="RR_RunButton">Run</button>\
			<button class="RR_StopButton">Stop</button>\
			<button class="RR_ClearButton">Clear</button>\
\
			<p>Output :</p>\
			<pre class="RR_Stdout"></pre>\
\
			<input type="text" class="RR_Stdin">\
		</div>';
    return $('.RR_RubyCode').parent().after(interactionZone);
  };

  RR_AppendText = function(txt, newline) {
    var msg;
    msg = $(prefix + '.RR_Stdout').html() + txt;
    if (newline === true) {
      msg += '\n';
    }
    $(prefix + '.RR_Stdout').html(msg);
    return $(prefix + '.RR_Stdin').val("");
  };

  RR_BindEventListener = function() {
    $('.RR_RunButton').click(RR_RunEvent);
    $('.RR_StopButton').click(RR_StopEvent);
    $('.RR_Stdin').keydown(function(e) {
      if (e.keyCode === 13) {
        RR_StdinEvent();
        return RR_AppendText($(prefix + '.RR_Stdin').val(), true);
      }
    });
    $('.RR_ClearButton').click(function() {
      return $(prefix + '.RR_Stdout').html('');
    });
    socket.on('stdout', function(output) {
      return RR_AppendText(output);
    });
    socket.on('stderr', function(output) {
      return RR_AppendText(output);
    });
    return socket.on('terminated', function(message) {
      return RR_AppendText(message, true);
    });
  };

  RR_RunEvent = function() {
    return socket.emit('run', $(prefix + '.RR_RubyCode').text());
  };

  RR_StopEvent = function() {
    return socket.emit('stop');
  };

  RR_StdinEvent = function() {
    return socket.emit('stdin', $(prefix + '.RR_Stdin').val());
  };

  RR_LoadJQuerry = function() {
    var headTag, jqTag;
    headTag = document.getElementsByTagName("head")[0];
    jqTag = document.createElement('script');
    jqTag.type = 'text/javascript';
    jqTag.src = 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js';
    jqTag.onload = function() {
      return $(RR_Main);
    };
    return headTag.appendChild(jqTag);
  };

  if (typeof jQuery === 'undefined') {
    RR_LoadJQuerry();
  } else {
    $(RR_Main);
  }

}).call(this);
