// Generated by CoffeeScript 1.4.0
(function() {
  var RubyCodeLauncher;

  RubyCodeLauncher = (function() {

    function RubyCodeLauncher() {}

    RubyCodeLauncher.prototype.setSocket = function(socket) {
      this.socket = socket;
    };

    RubyCodeLauncher.prototype.start = function(code) {
      return console.log('Code to execute is : ' + code);
    };

    RubyCodeLauncher.prototype.stop = function() {
      console.log('Stop execution code asked');
      this.socket.emit('stdout', 'stdout from ruby');
      return this.socket.emit('stderr', 'stderr from ruby');
    };

    RubyCodeLauncher.prototype.stdin = function(input) {
      return console.log('input is : ' + input);
    };

    return RubyCodeLauncher;

  })();

  module.exports = RubyCodeLauncher;

}).call(this);
