// Generated by CoffeeScript 1.9.3
(function() {
  var RubyCodeLauncher, spawn;

  spawn = require('child_process').spawn;

  RubyCodeLauncher = (function() {
    function RubyCodeLauncher() {}

    RubyCodeLauncher.prototype.ruby = void 0;

    RubyCodeLauncher.prototype.setSocket = function(socket) {
      this.socket = socket;
    };

    RubyCodeLauncher.prototype.start = function(code) {
      if (this.isRubyRunning()) {
        this.stop();
      }
      this.ruby = spawn('ruby', ['-e', code]);
      this.ruby.stdout.on('data', (function(_this) {
        return function(data) {
          return _this.socket.emit('stdout', data.toString());
        };
      })(this));
      this.ruby.stderr.on('data', (function(_this) {
        return function(data) {
          return _this.socket.emit('stderr', data.toString());
        };
      })(this));
      return this.ruby.on('close', (function(_this) {
        return function(code) {
          var msg;
          if (code === null) {
            msg = "Ruby script killed\n";
          } else {
            msg = "Terminated with code : " + code + "\n";
          }
          _this.socket.emit('terminated', msg);
          return _this.ruby = void 0;
        };
      })(this));
    };

    RubyCodeLauncher.prototype.stop = function() {
      if (this.isRubyRunning()) {
        this.ruby.kill();
        return this.ruby = void 0;
      }
    };

    RubyCodeLauncher.prototype.stdin = function(input) {
      if (this.isRubyRunning()) {
        this.ruby.stdin.write(input + '\n');
        return this.socket.emit('approvedInput', input);
      }
    };

    RubyCodeLauncher.prototype.isRubyRunning = function() {
      return this.ruby != null;
    };

    return RubyCodeLauncher;

  })();

  module.exports = RubyCodeLauncher;

}).call(this);
