// Generated by CoffeeScript 1.4.0
(function() {
  var http, io, server;

  http = require('http');

  io = require('socket.io');

  server = http.createServer();

  io = io.listen(server);

  io.sockets.on('connection', function(socket) {
    socket.on('run', function(code) {
      return console.log('Code to execute is : \n' + code);
    });
    socket.on('stop', function() {
      console.log('Stop execution code asked');
      return socket.emit('stdout', 'taaaaaaaataaaaaa yoyoooooooooooooooo');
    });
    return socket.on('stdin', function(input) {
      return console.log('input is : ' + input);
    });
  });

  server.listen(8080);

}).call(this);
